roll:
  description: 'Simulates a dice roll in a variety of ways, depending on the given inputs.'
  usage: 'roll [dice] [+/-F] [flags]'
  parameters:
    - 'The following dice formats are supported:'
    - 'NdS+/-F (usage 1d10, d10, 3d6+3, 2d20-5) rolls N dice with S sides and adds or subtracts given offset F.'
    - 'min-max+/-F (usage 1-10, 1-3+5, 1-20-3) rolls one dice between min and max, then adds or subtracts given offset F.'
    - 'S+/-F (usage 10, 5+3, 4-1) rolls one dice between 1 and S, inclusive, and adds or subtracts given offset F.'
    - 'Empty (no dice arguments given) rolls one dice between 1 and 10 with no offset.'
    -
    - 'The following flags are supported:'
    - '--successes: explodes critical successes as defined in the settings. Defaults to exploding 10s.'
    - '--sum: outputs sum of all dice rolls.'
  timeout: 50
  icon: 'https://emojipedia-us.s3.amazonaws.com/thumbs/160/google/56/game-die_1f3b2.png'
  results:
    crit fail:
      message: <%= ENV['CRIT_FAIL'] %>
      thumbnail: 'https://emojipedia-us.s3.amazonaws.com/thumbs/160/google/6/skull_1f480.png'
    fail:
      message: <%= ENV['BAD'] %>
      thumbnail: 'https://emojipedia-us.s3.amazonaws.com/thumbs/160/google/40/thumbs-down-sign_1f44e.png'
    average:
      message: <%= ENV['AVERAGE'] %>
      thumbnail: 'https://emojipedia-us.s3.amazonaws.com/thumbs/160/google/40/ok-hand-sign_1f44c.png'
    success:
      message: <%= ENV['SUCCESS'] %>
      thumbnail: 'https://emojipedia-us.s3.amazonaws.com/thumbs/160/google/6/confetti-ball_1f38a.png'
    crit success:
      message: <%= ENV['CRIT_SUCCESS'] %>
      thumbnail: 'https://emojipedia-us.s3.amazonaws.com/thumbs/160/google/6/crown_1f451.png'
    failure:
      message: <%= ENV['FAILURE'] %>
      description: 'You entered an invalid dice format. See `help roll` for valid formats.'
      thumbnail: 'https://emojipedia-us.s3.amazonaws.com/thumbs/160/google/6/cross-mark_274c.png'

random:
  description: 'Generates a random number between 0 and 1, 0 and `max` or `min` and `max`'
  usage: 'random [min/max] [max]'
  icon: 'http://emojipedia-us.s3.amazonaws.com/cache/fc/6f/fc6f0857b42e4c04a29e630c0bd7ce6a.png'
  results:
    crit fail:
      message: "Wow! You're dead!"
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/ab/04/ab0411dd94f212b655cba7f9df4080dc.png'
    fail:
      message: 'What a bad roll.'
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/7e/2a/7e2add5f86c01e6c39acd95cc151dd77.png'
    average:
      message: 'Meh, you did alright.'
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/4e/ed/4eed9ab32623b203e4823d77f69e7302.png'
    success:
      message: 'Nice one!'
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/5f/96/5f96fbfff67b418ee72fe1441c2120da.png'
    crit success:
      message: 'Wow! A critical success!'
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/a9/fd/a9fd26d9a700d63f5971e26d8e2aa787.png'

rollfor:
  description: 'Rolls Nd10 for a given character where N is the sum of their attributes.'
  usage: 'rollfor [character], [attributes] [+/-F] [flags]'
  parameters:
    - 'character: Alphanumeric identifier for a particular character. Character must exist.'
    - 'attributes: Space-delimited list of attributes used to determine number of dice to roll.'
    - 'f: Offset to add or subtract from the results. Must begin with + or -.'
    - 'The following flags are supported:'
    - '--successes: explodes critical successes as defined in the settings. Defaults to exploding 10s.'
    - '--sum: outputs sum of all dice rolls.'
  icon: 'http://emojipedia-us.s3.amazonaws.com/cache/a9/fd/a9fd26d9a700d63f5971e26d8e2aa787.png'
  results:
    crit fail:
      message: "Wow! You're dead!"
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/ab/04/ab0411dd94f212b655cba7f9df4080dc.png'
    fail:
      message: 'What a bad roll.'
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/7e/2a/7e2add5f86c01e6c39acd95cc151dd77.png'
    average:
      message: 'Meh, you did alright.'
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/4e/ed/4eed9ab32623b203e4823d77f69e7302.png'
    success:
      message: 'Nice one!'
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/5f/96/5f96fbfff67b418ee72fe1441c2120da.png'
    crit success:
      message: 'Wow! A critical success!'
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/a9/fd/a9fd26d9a700d63f5971e26d8e2aa787.png'
    failure:
      message: 'Failure...'
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/13/6e/136e9598cf792b90fa8c9c57e25545f8.png'


create:
  description: 'Create a character with the given identifier. Identifier must be unique. Additional attributes may be provided.'
  usage: 'create <identifier> [attribute: value, ...]'
  parameters:
  icon: 'http://emojipedia-us.s3.amazonaws.com/cache/49/d3/49d3a18cd6bdbd5ece46301ea890f24e.png'
  color: 0x28b8ff
  results:
    success:
      message: 'Success!'
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/63/24/63242c36f558553455bd96b10195dff2.png'
    failure:
      message: 'Failure...'
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/13/6e/136e9598cf792b90fa8c9c57e25545f8.png'

set:
  description: "Sets a character's attributes to the given values."
  usage: 'set character: <character>, [attribute: value...]'
  parameters:
  icon: 'http://emojipedia-us.s3.amazonaws.com/cache/b3/84/b384942abd3e41ee0a02ce2b2581ba72.png'
  color: 0x28b8ff
  results:
    success:
      message: 'Success!'
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/6f/85/6f85601457fdc057c43d7173652a4667.png'
    failure:
      message: 'Failure...'
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/42/62/42625b9cf85cbdc83e454381c2357b30.png'

sheet:
  description: "Displays a character's profile sheet."
  usage: 'sheet <identifier>'
  parameters:
  icon: 'http://emojipedia-us.s3.amazonaws.com/cache/e1/f7/e1f73959273a87ae04548193534ace11.png'
  color: 0x28b8ff
  results:
    failure:
      description: 'Try searching for a different character.'
      thumbnail: 'http://emojipedia-us.s3.amazonaws.com/cache/42/62/42625b9cf85cbdc83e454381c2357b30.png'
  emojis:
    -
      - '🇧'
      - 'checked_show_page(1)'
    -
      - '🇦'
      - 'checked_show_page(2)'
    -
      - '🇸'
      - 'checked_show_page(3)'
    -
      - '🇲'
      - 'checked_show_page(4)'
    -
      - '🇪'
      - 'checked_show_page(5)'
    -
      - '⏹'
      - 'stop_pages'
    -
      - '❓'
      - 'show_help'

botpermissions:
  description: "Returns a list of God Machine's permissions."
  usage: 'botpermissions'

options:
  separator: ','
  key_separator: ':'
